# Copyright (C) 2024 bytesatwork AG - https://www.bytesatwork.io
# Released under the MIT license (see COPYING.MIT for the terms)

#@TYPE: Machine
#@NAME: byteDEVKIT IMX93
#@DESCRIPTION: byteDEVKIT IMX93 by bytesatwork AG

require include/byteengine-imx93.inc

KERNEL_DEFCONFIG = "bytedevkit_imx93_defconfig"
KERNEL_DEVICETREE = "freescale/${KERNEL_DEVICETREE_BASENAME}.dtb"
KERNEL_DEVICETREE_BASENAME = "imx93-bytedevkit"

UBOOT_CONFIG ??= "sd"
UBOOT_CONFIG[sd]   = "${UBOOT_CONFIG_BASENAME}_defconfig,sdcard"
UBOOT_DTB_NAME = "${KERNEL_DEVICETREE_BASENAME}.dtb"

IMXBOOT_TARGETS = "flash_singleboot"

SERIAL_CONSOLES = "115200;ttyLP0"

WKS_FILE = "byteengine-imx93-sdcard.wks.in"
