# Copyright (C) 2024 bytesatwork AG - https://www.bytesatwork.io
# Released under the MIT license (see COPYING.MIT for the terms)

#@TYPE: Machine
#@NAME: byteDEVKIT IMX8MP
#@DESCRIPTION: byteDEVKIT IMX8MP by bytes at work AG

require include/byteengine-imx8mp.inc

KERNEL_DEFCONFIG = "bytedevkit_imx8mp_defconfig"
KERNEL_DEVICETREE = " \
	freescale/imx8mp-bytedevkit.dtb \
	freescale/imx8mp-bytedevkit-v2.dtb \
"

UBOOT_CONFIG ??= "sd"
UBOOT_CONFIG[sd] = "imx8mp_bytedevkit_defconfig,sdcard"

# Set u-boot DTB
UBOOT_DTB_NAME = "imx8mp-bytedevkit.dtb"

# Set imx-mkimage boot target
IMXBOOT_TARGETS = "${@bb.utils.contains('UBOOT_CONFIG', 'fspi', 'flash_evk_flexspi', 'flash_evk', d)}"

# Set Serial console (aliased in dt from uart2)
SERIAL_CONSOLES = "115200;ttymxc0"

WKS_FILE = "byteengine-imx8mp-sdcard.wks.in"
